### ISSUE TITLE
Arduino sketch

### ISSUE THREAD

**Issue by fedeUD1971** [silvioallena/MOTORISED_CAMERA_SLIDER_WITH_PAN_AND_TILT#1]
Ciao Silvio. Ho visto i tuoi video e quelli di Isaac879. Ottimo lavoro.
Non trovo lo sketch da caricare sulla esp32

**Comment by silvioallena** [comment]
Buonasera. Hai perfettamente ragione. 
Chiedo scusa per la dimenticanza. 
Ho aggiunto la cartella con gli sketch sia per controller PS3 che per controller PS4.
Nel caso avessi dimenticato altro non esitare a farmelo sapere.
Grazie.

**Comment by silvioallena** [comment]
Chiedo scusa.
Aggiorno subito il github.

Il giorno mar 14 mar 2023 alle ore 19:39 fedeUD1971 <
***@***.***> ha scritto:
